version: 2
jobs:
  build:
    docker:
      - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Dependencies
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./.venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Run Tests
          command: |
            . .venv/bin/activate
            nosetests -w test

      - store_artifacts:
          path: test-reports
          destination: test-reports

      - container:
          name: Containerize
          command: |
            docker build . -t testsquad/hive
